# Pandas

<svg xmlns="http://www.w3.org/2000/svg" width="480" height="200" viewBox="0 0 600 250">
<rect x="60" y="20" width="480" height="170" rx="14" fill="#ffffff" stroke="#9aa0a6" stroke-width="3"/>
<rect x="60" y="20" width="480" height="38" rx="14" fill="#2d2f33"/>
<rect x="60" y="44" width="480" height="14" fill="#2d2f33"/>
<text x="80" y="47" fill="#f2f2f2" font-family="monospace" font-size="22">patient_id</text>
<text x="270" y="47" fill="#f2f2f2" font-family="monospace" font-size="22">age</text>
<text x="400" y="47" fill="#f2f2f2" font-family="monospace" font-size="22">ward</text>
<line x1="250" y1="20" x2="250" y2="189" stroke="#9aa0a6" stroke-width="2"/>
<line x1="380" y1="20" x2="380" y2="189" stroke="#9aa0a6" stroke-width="2"/>
<line x1="61" y1="102" x2="539" y2="102" stroke="#dadce0" stroke-width="2"/>
<line x1="61" y1="146" x2="539" y2="146" stroke="#dadce0" stroke-width="2"/>
<text x="80" y="90" fill="#1b1b1b" font-family="monospace" font-size="22">P0001</text>
<text x="270" y="90" fill="#1b1b1b" font-family="monospace" font-size="22">66</text>
<text x="400" y="90" fill="#1b1b1b" font-family="monospace" font-size="22">ICU</text>
<text x="80" y="134" fill="#1b1b1b" font-family="monospace" font-size="22">P0002</text>
<text x="270" y="134" fill="#c53030" font-family="monospace" font-size="22">NaN</text>
<text x="400" y="134" fill="#1b1b1b" font-family="monospace" font-size="22">ICU</text>
<text x="80" y="178" fill="#1b1b1b" font-family="monospace" font-size="22">P0003</text>
<text x="270" y="178" fill="#1b1b1b" font-family="monospace" font-size="22">41</text>
<text x="400" y="178" fill="#1b1b1b" font-family="monospace" font-size="22">ONCO</text>
<text x="300" y="235" fill="#2d2f33" font-family="Helvetica, Arial, sans-serif" font-size="26" font-weight="bold" text-anchor="middle">The DataFrame</text>
</svg>

[Each question is followed by an empty cell: write your answer there. Use pandas for all questions, unless stated otherwise.]

In [1]:
import pandas as pd

## 1. Loading a CSV

Get the data first: open [`patients.csv`](https://github.com/MICS-Lab/MS_SanteNum2026/blob/master/Programming01/data/patients.csv) on GitHub, click *Raw* ([direct link](https://raw.githubusercontent.com/MICS-Lab/MS_SanteNum2026/master/Programming01/data/patients.csv)), select everything (`Ctrl+A`), copy, and paste it into a new text file called `patients.csv` on your PC. It is a synthetic ward export of $240$ patients, the same for everybody.

Then set `path` in the cell below to where you saved the file, e.g. `"C:/Users/me/Documents/patients.csv"` or `"/home/me/Documents/patients.csv"` (a path relative to this notebook works too). The cell must print `True`; if it prints `False`, the path is wrong.

In [2]:
from pathlib import Path

path = Path("../data/patients.csv")  # adjust to where you saved the file
path.exists()

Read the file into a `DataFrame` called `df` (`pd.read_csv`), then look at its first rows (`.head()`). A `DataFrame` is a table: named columns, each one with its own type.

In [3]:
df = pd.read_csv(path)
df.head()

  patient_id   age sex   ward   admission  los_days      outcome
0      P0001  66.0   F    ICU  2024-04-21       6.4  transferred
1      P0002  14.0   F    ICU  2024-04-14      10.6  transferred
2      P0003  73.0   M    ICU  2024-07-09       8.6  transferred
3      P0004   6.0   F  PEDIA  2024-09-09       7.0   discharged
4      P0005  63.0   M   ONCO  2024-06-08       9.1   discharged

Print the shape of the table (`.shape`) and the type of each column (`.dtypes`).
Which columns did pandas read as numbers, and which ones as text (`str`)?

In [4]:
df.shape, df.dtypes

((240, 7),
 patient_id        str
 age           float64
 sex               str
 ward              str
 admission         str
 los_days      float64
 outcome           str
 dtype: object)

`.info()` gives both at once, plus the number of values that are actually there in each column. Call it, and look for the column that is short of a few values.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   patient_id  240 non-null    str
 1   age         232 non-null    float64
 2   sex         240 non-null    str
 3   ward        240 non-null    str
 4   admission   240 non-null    str
 5   los_days    240 non-null    float64
 6   outcome     240 non-null    str
dtypes: float64(2), str(5)
memory usage: 13.3 KB

## 2. Dropping the missing values

A hole in the file (an empty cell in the CSV) is read as `NaN` ($8$ ages are missing here).
Count the missing values per column (`.isna().sum()`).

In [6]:
df.isna().sum()

patient_id    0
age           8
sex           0
ward          0
admission     0
los_days      0
outcome       0
dtype: int64

Build `clean`, the table without the rows that have a missing value (`.dropna()`), and compare the number of rows before and after (`len`).
`.dropna()` returns a new table, it does not change `df`.

In [7]:
clean = df.dropna()
len(df), len(clean)

(240, 232)

## 3. Changing the type of a column (`.astype`)

`age` was read as a float, only because of the holes. Now that they are gone, convert it to an integer: `clean["age"] = clean["age"].astype("int64")`.
Check with `.dtypes` that the column changed.

In [8]:
clean["age"] = clean["age"].astype("int64")
clean.dtypes

patient_id        str
age             int64
sex               str
ward              str
admission         str
los_days      float64
outcome           str
dtype: object

Two other useful conversions: `ward` holds $5$ repeated labels, so `.astype("category")` is both faster and smaller, and `admission` is a date written as text, which `pd.to_datetime` turns into a real date.
Convert both, then print `.dtypes` again.

In [9]:
clean["ward"] = clean["ward"].astype("category")
clean["admission"] = pd.to_datetime(clean["admission"])
clean.dtypes

patient_id               str
age                    int64
sex                      str
ward                category
admission     datetime64[us]
los_days             float64
outcome                  str
dtype: object

## 4. Selecting one column

`clean["age"]` is one column, a `Series` (one array, plus an index).
Print it, then its mean, its minimum and its maximum (`.mean()`, `.min()`, `.max()`).

In [10]:
ages = clean["age"]
ages.mean(), ages.min(), ages.max()

(np.float64(50.866379310344826), np.int64(1), np.int64(99))

On a column of text or of categories, `.value_counts()` counts each label.
How many stays per ward? And per outcome?

In [11]:
clean["ward"].value_counts(), clean["outcome"].value_counts()

(ward
 ICU       73
 CARDIO    61
 ONCO      38
 PEDIA     34
 GERIA     26
 Name: count, dtype: int64,
 outcome
 discharged     155
 transferred     58
 deceased        19
 Name: count, dtype: int64)

## 5. Selecting a subset of columns

With a list inside the brackets, you get a table instead of a column: `clean[["patient_id", "ward"]]`.
Build `summary`, the table with only `patient_id`, `ward`, `age` and `los_days`, and show its first rows.

In [12]:
summary = clean[["patient_id", "ward", "age", "los_days"]]
summary.head()

  patient_id   ward  age  los_days
0      P0001    ICU   66       6.4
1      P0002    ICU   14      10.6
2      P0003    ICU   73       8.6
3      P0004  PEDIA    6       7.0
4      P0005   ONCO   63       9.1

Note the difference: `clean["age"]` is a `Series`, `clean[["age"]]` is a `DataFrame` of one column. Print the `type` of both.

In [13]:
type(clean["age"]), type(clean[["age"]])

(pandas.Series, pandas.DataFrame)

## 6. Applying a function to a column (`.apply`)

`.apply` runs a function on every value of a column and returns the results as a new column.
Write a function `stay_length(days)` that returns `"short"` under $3$ days, `"long"` over $10$, and `"medium"` in between, then add the column `summary["stay"] = summary["los_days"].apply(stay_length)`.
Count the result with `.value_counts()`.

In [14]:
def stay_length(days):
    if days < 3:
        return "short"
    if days > 10:
        return "long"
    return "medium"


summary["stay"] = summary["los_days"].apply(stay_length)
summary["stay"].value_counts()

stay
medium    128
long       54
short      50
Name: count, dtype: int64

`.apply` also takes a lambda, which is handy for a one liner.
Add a column `age_group` holding `"minor"` or `"adult"`, with `summary["age"].apply(lambda a: ...)`.

In [15]:
summary["age_group"] = summary["age"].apply(lambda a: "minor" if a < 18 else "adult")
summary.head()

  patient_id   ward  age  los_days    stay age_group
0      P0001    ICU   66       6.4  medium     adult
1      P0002    ICU   14      10.6    long     minor
2      P0003    ICU   73       8.6  medium     adult
3      P0004  PEDIA    6       7.0  medium     minor
4      P0005   ONCO   63       9.1  medium     adult

## 7. Saving as a CSV

Write `summary` to `patients_summary.csv` with `.to_csv("patients_summary.csv", index=False)`.
`index=False` drops the row numbers, which are not data: without it, the file gets an extra nameless first column.

In [16]:
summary.to_csv("patients_summary.csv", index=False)

Read the file back (`pd.read_csv`) and check that you get the same table (`.head()`, `.shape`).
Open it with the shell too, as in the previous session: `!head -3 patients_summary.csv`.

In [17]:
again = pd.read_csv("patients_summary.csv")
again.shape, again.head()

((232, 6),
   patient_id   ward  age  los_days    stay age_group
 0      P0001    ICU   66       6.4  medium     adult
 1      P0002    ICU   14      10.6    long     minor
 2      P0003    ICU   73       8.6  medium     adult
 3      P0004  PEDIA    6       7.0  medium     minor
 4      P0005   ONCO   63       9.1  medium     adult)